### PR TITLE
Added service classes as parameters

### PR DESCRIPTION
**Pull request by dragosprotung**
This is mostly because I needed to overwrite the AclIdentifier class and it's a bit easier than writing a compiler pass

### CODE REVIEW

**Comment by dragosprotung** [comment]
Should be ok to merge, Travis failed because of some timeouts.

**Comment by ProPheT777** [comment]
IMO You should consider replace the entire service instead of the class signature of the service because most of time you will require your own dependencies and the service definition have a contract against the constructor of class that we define, but wrong with your needs. 

Moreover, you can make configurable those services via the configuration and replace it at compile time. Here an example may be more clear of what I mean : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ConfigurationReference.md Look at the driver key, specify a service instead of a class. 

What do you think about this approach ?

**Comment by dragosprotung** [comment]
I do not quite understand how this can apply here.  What I want to achieve is simply to add a bit more behavior on one of the methods in AclIdentifier. Right now I have a custom CompilerPass that replaces the class of the service with a custom one.

**Comment by ProPheT777** [comment]
Yes it can be first move to run into this. I'm agree for your current need you don't need this. I keep this in mind

**Comment by dragosprotung** [comment]
Thanks !

The reason that i needed to add behavior, is the reason described in #7

**Pull request merged**
