### PR TITLE
Added casting and boolean where values for stricter DBs (ex: PostgreSQL)

### PR DESCRIPTION
**Pull request by dragosprotung**

### CODE REVIEW

**Comment by AlexDpy** [comment]
Thank you @dragosprotung for reporting that issue.

Tests are failing here because they use SQLite. And we also need to support mysql.
I just made another pull request ( #5 ) where tests are green with sqlite, pgsql and mysql.

Tell me what you think about it.

**Comment by dragosprotung** [comment]
I just pushed a fix for the tests. I really do not know how I missed the fail when running the tests.

I just saw that you also just did this. Have a look at my pull request (#4) as well.

**Comment by dragosprotung** [comment]
I see in your commit that you convert the oidReference to CHAR(100). Is there a reason for it ? I thought it's always an integer.

**Comment by AlexDpy** [comment]
I just pushed a travis improvement on master branch. Travis will now run tests against sqlite, pgsql and mysql.
You can now rebase your branch and let travis do his job :)

You can see in my pull request ( #5 ) that I have an error with mysql on the CAST(). If you have any idea to solve this...

About the CAST on object_identifier, you can see here (https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Acl/Dbal/Schema.php#L112) that object_identifier is a varchar 100. And the $oidReference could be a string in some cases.
So we can not cast is as an integer. But we can cast the oidReference as a char(100).. I just have a bug with it on Mysql (I don't have this bug on my local machine, but travis has :( )

**Comment by dragosprotung** [comment]
You are right.

It seems that now the problem is fixed. I also tried your branch on my project and everything looks good.
I see no reason not to merge this in the master branch.

Thank you !

**Pull request closed without merging**
